/var/log/suricata-boot-prune.log
/var/log/suricata-start.log
/var/log/suricata-runner-update.log
/var/log/post-cfg.sh.log
/var/log/suricata/suricata.log {
    size 256k
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
